version: '3.8'

services:
  portofolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-portofolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped